### ISSUE TITLE
Newest release?

### ISSUE THREAD

**Issue by sigilworks** [apocas/dockerode-compose#18]
I see the `docker-compose down` functionality was added back in February, but doesn't seem to be in the latest release in NPM (`1.2.2`). Would it be possible to have to latest version of this fantastic library released?

**Comment by sigilworks** [comment]
@apocas , I'm wondering if there's a schedule/release roadmap? (I don't want to necessarily fork the project, if it's something that you just plan to release in a week or three anyways, or as part of a normal schedule.) 

Thank you for any information. 😄

**Comment by apocas** [comment]
just published v1.3.1 :)
I'm going to publish as soon there is new features.
Unfortunately I've been overwhelmed with work lately and this got temporarily neglected :)

**Comment by sigilworks** [comment]
Thank you, @apocas . I'm very grateful for the great work you've done here!
