### ISSUE TITLE
`buildNetworks` broken after refactoring

### ISSUE THREAD

**Issue by sigilworks** [apocas/dockerode-compose#20]
The `buildNetworks` function in the latest release of `dockerode-compose` (v1.3.1) is broken.

It seems there was a refactoring in commit [`dea731526da26549562c242a8724692eb7a89144`](https://github.com/apocas/dockerode-compose/commit/dea731526da26549562c242a8724692eb7a89144) back in May 2021 that broke `buildNetworks` in [serviceTools.js](https://github.com/apocas/dockerode-compose/blob/main/lib/servicesTools.js#L414-L431).

In the first conditional (if `serviceNetworks` is an array):
* `projectName` is not available/in scope anymore in this new location at [line 416](https://github.com/apocas/dockerode-compose/blob/main/lib/servicesTools.js#L416)
* neither is `serviceName` on [line 425](https://github.com/apocas/dockerode-compose/blob/main/lib/servicesTools.js#L425)
* nor the `opts` object at [line 427](https://github.com/apocas/dockerode-compose/blob/main/lib/servicesTools.js#L427)

So calling `Compose#up` on a `docker-compose.yml` that has services with networks defined causes the operation to fail, when it gets to [services.js line 168](https://github.com/apocas/dockerode-compose/blob/main/lib/services.js#L168).

**Comment by apocas** [comment]
Fixed on https://github.com/apocas/dockerode-compose/pull/22
